### ISSUE TITLE
Trial version disappeared after restart.

### ISSUE THREAD

**Issue by LegendFoxx** [gato-louco/exitlag-account-activator#31] opened 2021-11-01 07:09 UTC
I did everything as instructed. After that, a notification from Windows appeared that the ExitLag was being used on another computer. And after restarting my PC, my trial version was completely gone.
![image](https://user-images.githubusercontent.com/83547955/139634816-58bfb7b8-d666-425b-b60a-451bbfca1fb1.png)

**Comment by UNITY51** [comment] 2021-11-01 07:32
> I did everything as instructed. After that, a notification from Windows appeared that the ExitLag was being used on another computer. And after restarting my PC, my trial version was completely gone. ![image](https://user-images.githubusercontent.com/83547955/139634816-58bfb7b8-d666-425b-b60a-451bbfca1fb1.png)

Bro its fixed (((

**Comment by takattowo** [comment] 2021-11-01 10:54
Well they did a server side checking on your current PC whether it matches with the current registered one, so it is impossible to do now. But there is still a way, by spoofing your PC to be matched with the registered, or, edit the ID that ExitLag gathered before it sends to the server which is easier. I'll be playing around with CE to see what can I find.

**Comment by gato-louco** [comment] 2021-11-01 12:43
DUPLICATE OF #26

**Closed** 2021-11-01 12:43 UTC
