### ISSUE TITLE
They know... about those gmail generator with dot.

### ISSUE THREAD

**Issue by illidank** [gato-louco/exitlag-account-activator#25] opened 2021-10-28 22:35 UTC
I was doing my routine and suddenly got a noti said that "account logged from another machine" then few moments later, they kick me out of my games, and kind force close the exitlag apps, then when i run it again, it said no vip days. Reg another account, worked for like 10-20 mins, then same thing happened.
I don't know if it's my problem alone, or we have to find another way.

**Comment by rosnuker** [comment] 2021-10-29 18:30
Same here, made 3 accounts from gmail with dot, exitlag suddenly exited while I was playing League of Legends, made 2 accounts with outlook, same outcome

**Comment by gato-louco** [comment] 2021-10-29 22:02
> Try to create another email. See if you still facing the same issue

**Comment by gato-louco** [comment] 2021-10-29 22:03
I mean, try to use emails without dot. Looks like it is a dupe of #26

**Closed** 2021-10-30 13:20 UTC
