### ISSUE TITLE
Patched

### ISSUE THREAD

**Issue by DIRIKtv** [gato-louco/exitlag-account-activator#26] opened 2021-10-29 05:05 UTC
Recently used this on my computer. I have used it many times in the past couple of months and has worked fine but today it doesn't work. When I make another account and run the script it shows up on the Exitlag website as 3 days but once you log into the Exitlag application that number will go to 0 days.

**Comment by MohamedWSalah** [comment] 2021-10-29 21:13
> Hey!
> 
> Cool, looks like now we need to hook the binary and use the same hwid that the account was generated.
> 
> For what you guys are saying, I can assume they implemented a check in the backend.
> 
> Good job, exitlag.
> 
> Guys, I don't intend to keep this project, unless there is some support. I don't have time to do it (I have to work). I don't use exitlag either.
> 
> Monetary support is going to help, because the time I'd spend working, I could work on Exitlag update.
> 
> Do I have the ability to update it? I sure do. But I need your support.
> 
> I think I am going to create a PayPal donate button and Bitcoin donation. What you guys think?

You have the full right to do that tbh gato, and dont force ur self tho

**Comment by MohamedWSalah** [comment] 2021-10-29 21:13
But if u know the problem, you can explain it here, and maybe anyone from the community can code it.

**Comment by gato-louco** [comment] 2021-10-29 21:56
Current Exitlag account activator works this way: 

- We connect to the websocket of exitlag login endpoint.
- We send a message saying "Hey, I am logging from this computer. This is the password, this is the email and this is the HWID of the computer". The HWID we send is a random one.
- ExitLag checks if the password and email matchs with one registered.
- Then it checks if the HWID was already used once to login into an account.
- If it was used before, so the user is trying to login with a computer that already got a trial.
- If it wasn't used before, it saves the HWID and set as already used and activate 3 days trial.
- Then, you login with a computer that the HWID was already saved as used [your computer], but once the account was already created with a random HWID, it just accepts.

Okay, what changed now is that the HWID used to create the account [we used a random one] must match to the one who is login in.

So, what we need to do:
Remember the first version o the HWID bypass, that is a executable? Well, it is going to be something similar.

- Reverse engineer the exitlag executable
- Find where it gets the HWID
 - Make a random hwid and save it to a file [the filename could be hwid.txt].
 - Change the hwid before it is send to exitlag login.

Simple, but the Reverse engineer part isn't easy,

**Comment by githubuser732** [comment] 2021-10-30 06:28
> Current Exitlag account activator works this way:
> 
> * We connect to the websocket of exitlag login endpoint.
> * We send a message saying "Hey, I am logging from this computer. This is the password, this is the email and this is the HWID of the computer". The HWID we send is a random one.
> * ExitLag checks if the password and email matchs with one registered.
> * Then it checks if the HWID was already used once to login into an account.
> * If it was used before, so the user is trying to login with a computer that already got a trial.
> * If it wasn't used before, it saves the HWID and set as already used and activate 3 days trial.
> * Then, you login with a computer that the HWID was already saved as used [your computer], but once the account was already created with a random HWID, it just accepts.
> 
> Okay, what changed now is that the HWID used to create the account [we used a random one] must match to the one who is login in.
> 
> So, what we need to do: Remember the first version o the HWID bypass, that is a executable? Well, it is going to be something similar.
> 
> * Reverse engineer the exitlag executable
> * Find where it gets the HWID
> * Make a random hwid and save it to a file [the filename could be hwid.txt].
> * Change the hwid before it is send to exitlag login.
> 
> Simple, but the Reverse engineer part isn't easy,

Gato, não sei você é brasileiro ou não mas esse projeto literalmente salvou minha vida cara, não tenho condições de assinar pois estou desempregado há anos e doaria dinheiro pra você continuar atualizando se eu tivesse, porém não tenho. Venho usando este método a mais ou menos dois ou três meses mas estou enfrentando o mesmo problema da galera ali em cima, no começo eu pensei que tinha alguma coisa a ver com todo mundo usando o mesmo site de gerar emails, porém mesmo criando um hotmail novo, o exitlag crasha do nada e diz que você tem 0 dias. Sei que é difícil pra você continuar trabalhando nisto sem estar ganhando nada mas você me ajudaria demais se continuasse!

**Comment by Borisizdabezt** [comment] 2021-10-30 10:37
run cmd with administrator and type py main.py,... then open task manager to end process "cmd.exe" (sorry for my bad English)

**Comment by Executorg** [comment] 2021-10-30 11:01
> run cmd with administrator and type py main.py,... then open task manager to end process "cmd.exe" (sorry for my bad English)

Нужно завершить процесс уже после того как скрипт активировал 3 дня? Я только что так попробовал закрыть через диспетчер и у меня вообще даже 3 дня активации не появились на сайте. В exitlage тоже.

**Comment by gosu821** [comment] 2021-10-30 11:17
i found the way keep trials but it is just u playing video or use laptop, pc
+when u create acc and use script to active 3 days, refresh tab for sure that 3 days then do not close that tab when u verifed and actived it
or close your browser keep it up

**Comment by minibruce** [comment] 2021-10-30 11:31
the point is HWID
when u close browser or program 
they may recheck ur HWID

**Comment by Borisizdabezt** [comment] 2021-10-30 11:54
> i found the way keep trials but it is just u playing video or use laptop, pc +when u create acc and use script to active 3 days, refresh tab for sure that 3 days then do not close that tab when u verifed and actived it or close your browser keep it open
> 
> ![hình ảnh_2021-10-30_181944](https://user-images.githubusercontent.com/58213619/139530907-83d1bf7b-ca12-406b-899b-4187e62d6f57.png) been using 5hours like that

không ông à, tụi exitlag nó check hwid chứ nó không ngu như ông tưởng

**Comment by Borisizdabezt** [comment] 2021-10-30 12:00
> Нужно завершить процесс уже после того как скрипт активировал 3 дня? Я только что так попробовал закрыть через диспетчер и у меня вообще даже 3 дня активации не появились на сайте. В exitlage тоже.

u need to wait for it when it activated likes 
![image](https://user-images.githubusercontent.com/90611639/139532010-905ab469-6c2f-4f67-b672-f46a4dafa406.png)
after it shows like that picture, u can close it or kill "cmd.exe" thru task manager

**Comment by Executorg** [comment] 2021-10-30 12:05
> > Нужно завершить процесс уже после того как скрипт активировал 3 дня? Я только что так попробовал закрыть через диспетчер и у меня вообще даже 3 дня активации не появились на сайте. В exitlage тоже.
> 
> u need to wait for it when it activated likes ![image](https://user-images.githubusercontent.com/90611639/139532010-905ab469-6c2f-4f67-b672-f46a4dafa406.png) after it shows like that picture, u can close it or kill "cmd.exe" thru task manager

yes. but after that if you restart exitlag the 3 days are gone. so your "run as admin" advice not working
С этим все понятно. Но потом 3 дня превращатся в 0 если закрыть exitlag, либо он сам закроется со временем

**Comment by Borisizdabezt** [comment] 2021-10-30 12:06
hmmm i'll see

**Comment by gosu821** [comment] 2021-10-30 12:07
> > i found the way keep trials but it is just u playing video or use laptop, pc +when u create acc and use script to active 3 days, refresh tab for sure that 3 days then do not close that tab when u verifed and actived it or close your browser keep it open
> > ![hình ảnh_2021-10-30_181944](https://user-images.githubusercontent.com/58213619/139530907-83d1bf7b-ca12-406b-899b-4187e62d6f57.png) been using 5hours like that
> 
> không ông à, tụi exitlag nó check hwid chứ nó không ngu như ông tưởng

thì như gato nói làm sao để biết rằng nó nghĩ mình dùng như 1 pc mới, chỉ hwid spoofer, và bỏ tiền mua
t thử lúc sau thì đúng 5 tiếng k sao, t tắt đi refresh lại được
đang thử spoofer của https://github.com/ALEHACKsp/hwid-bypass

**Comment by gosu821** [comment] 2021-10-30 12:13
it's hard to make Reverse-Engineering the exitlag executable 
took a lot time, it's not worth when you take your time doing it
simple solution is maybe go back a job we do, then pay for exitlag

**Comment by Borisizdabezt** [comment] 2021-10-30 12:18
i have some ideas
dont use the same password for every exitlag account u have created
run exitlag as administrator and uncheck keep me connected at login screen (u must activated this account)

**Comment by gosu821** [comment] 2021-10-30 12:23
> i have some ideas dont use the same password for every exitlag account u have created run exitlag as administrator and uncheck keep me connected at login screen (u must activated this account)

chính xác nhưng gì tôi làm

**Comment by Borisizdabezt** [comment] 2021-10-30 12:24
haiz
tôi code fix bug này đây

**Comment by gato-louco** [comment] 2021-10-30 12:48
EVERYONE: ENGLISH ONLY.

IF I SEE ANY OTHER MESSAGE FROM ANOTHER LANGUAGE, THE AUTOR OF THE MESSAGE WILL BE BANNED FROM THE THE REPOSITORY.

LET'S KEEP THE CHAT CLEAN AND UNDERSTANDABLE FOR EVERYONE.

**Comment by gato-louco** [comment] 2021-10-30 12:52
> > Нужно завершить процесс уже после того как скрипт активировал 3 дня? Я только что так попробовал закрыть через диспетчер и у меня вообще даже 3 дня активации не появились на сайте. В exitlage тоже.
> 
> u need to wait for it when it activated likes 
> ![image](https://user-images.githubusercontent.com/90611639/139532010-905ab469-6c2f-4f67-b672-f46a4dafa406.png)
> after it shows like that picture, u can close it or kill "cmd.exe" thru task manager

This does not make sense. What is your Exitlag version?

**Comment by Borisizdabezt** [comment] 2021-10-30 12:53
> > > Нужно завершить процесс уже после того как скрипт активировал 3 дня? Я только что так попробовал закрыть через диспетчер и у меня вообще даже 3 дня активации не появились на сайте. В exitlage тоже.
> > 
> > 
> > u need to wait for it when it activated likes
> > ![image](https://user-images.githubusercontent.com/90611639/139532010-905ab469-6c2f-4f67-b672-f46a4dafa406.png)
> > after it shows like that picture, u can close it or kill "cmd.exe" thru task manager
> 
> This does not make sense. What is your Exitlag version?

v4.198 lol

**Comment by gato-louco** [comment] 2021-10-30 12:53
> > > i found the way keep trials but it is just u playing video or use laptop, pc +when u create acc and use script to active 3 days, refresh tab for sure that 3 days then do not close that tab when u verifed and actived it or close your browser keep it open
> > > ![hình ảnh_2021-10-30_181944](https://user-images.githubusercontent.com/58213619/139530907-83d1bf7b-ca12-406b-899b-4187e62d6f57.png) been using 5hours like that
> > 
> > không ông à, tụi exitlag nó check hwid chứ nó không ngu như ông tưởng
> 
> thì như gato nói làm sao để biết rằng nó nghĩ mình dùng như 1 pc mới, chỉ hwid spoofer, và bỏ tiền mua
> t thử lúc sau thì đúng 5 tiếng k sao, t tắt đi refresh lại được
> đang thử spoofer của https://github.com/ALEHACKsp/hwid-bypass

Off course you can use a spoofer and create an account. The problem is, you are likely going to be banned from the games anti cheat if you use a spoofer

**Comment by gato-louco** [comment] 2021-10-30 12:56
> it's hard to make Reverse-Engineering the exitlag executable 
> took a lot time, it's not worth when you take your time doing it
> simple solution is maybe go back a job we do making money, then pay for exitlag

Nah, it is not hard. It is going to take some hours, but it is likely Worth if people support. Exitlag doesn't have any virtualization.

**Comment by gato-louco** [comment] 2021-10-30 12:56
> it's hard to make Reverse-Engineering the exitlag executable 
> took a lot time, it's not worth when you take your time doing it
> simple solution is maybe go back a job we do making money, then pay for exitlag

Btw, what did you reverse engineered Exitlag for?

**Comment by gato-louco** [comment] 2021-10-30 12:57
> i have some ideas
> dont use the same password for every exitlag account u have created
> run exitlag as administrator and uncheck keep me connected at login screen (u must activated this account)
> 

Nop. It doesn't work.
I already find a way to use any other password btw.

**Comment by Borisizdabezt** [comment] 2021-10-30 12:59
i think i will build a program that runs Exitlag activator first and run exitlag second

**Comment by gato-louco** [comment] 2021-10-30 13:03
> haiz
> tôi code fix bug này đây

Ow. So u probably know reverse engineering, assembly, C/C++, websocket connections, ways to get hwid and a bunch of experience.

Feel free to share your method with me (if it works, I just gonna keep it private, or as u wish) on my email (it is on my profile)

**Comment by gato-louco** [comment] 2021-10-30 13:06
> i think i will build a program that runs Exitlag activator first and run exitlag second

Go ahead. If the verification is server side, as I expect, it is not going to work. Unless they made a really dumb logic mistake.

**Comment by gato-louco** [comment] 2021-10-30 13:08
> > > > Нужно завершить процесс уже после того как скрипт активировал 3 дня? Я только что так попробовал закрыть через диспетчер и у меня вообще даже 3 дня активации не появились на сайте. В exitlage тоже.
> > > 
> > > 
> > > u need to wait for it when it activated likes
> > > ![image](https://user-images.githubusercontent.com/90611639/139532010-905ab469-6c2f-4f67-b672-f46a4dafa406.png)
> > > after it shows like that picture, u can close it or kill "cmd.exe" thru task manager
> > 
> > This does not make sense. What is your Exitlag version?
> 
> v4.198 lol
> 

LAST UPDATE

4.201

Release date:

16/09/2021

**Comment by gosu821** [comment] 2021-10-30 13:09
> > it's hard to make Reverse-Engineering the exitlag executable
> > took a lot time, it's not worth when you take your time doing it
> > simple solution is maybe go back a job we do making money, then pay for exitlag
> 
> Btw, what did you reverse engineered Exitlag for?

I did reverse engineered on some android vpn root phone
But i thought u tried to reverse before 😆 cause u said that it was hard, so didnt even try 😆

**Comment by gosu821** [comment] 2021-10-30 13:10
> > haiz
> > tôi code fix bug này đây
> 
> Ow. So u probably know reverse engineering, assembly, C/C++, websocket connections, ways to get hwid and a bunch of experience.
> 
> Feel free to share your method with me (if it works, I just gonna keep it private, or as u wish) on my email (it is on my profile)

That's not me, some guys remade your work for his personality

**Comment by Borisizdabezt** [comment] 2021-10-30 13:13
I just remade it easy for those who are new to python men

**Comment by gato-louco** [comment] 2021-10-30 13:17
> > Current Exitlag account activator works this way:
> > 
> > * We connect to the websocket of exitlag login endpoint.
> > * We send a message saying "Hey, I am logging from this computer. This is the password, this is the email and this is the HWID of the computer". The HWID we send is a random one.
> > * ExitLag checks if the password and email matchs with one registered.
> > * Then it checks if the HWID was already used once to login into an account.
> > * If it was used before, so the user is trying to login with a computer that already got a trial.
> > * If it wasn't used before, it saves the HWID and set as already used and activate 3 days trial.
> > * Then, you login with a computer that the HWID was already saved as used [your computer], but once the account was already created with a random HWID, it just accepts.
> > 
> > Okay, what changed now is that the HWID used to create the account [we used a random one] must match to the one who is login in.
> > 
> > So, what we need to do: Remember the first version o the HWID bypass, that is a executable? Well, it is going to be something similar.
> > 
> > * Reverse engineer the exitlag executable
> > * Find where it gets the HWID
> > * Make a random hwid and save it to a file [the filename could be hwid.txt].
> > * Change the hwid before it is send to exitlag login.
> > 
> > Simple, but the Reverse engineer part isn't easy,
> 
> Gato, não sei você é brasileiro ou não mas esse projeto literalmente salvou minha vida cara, não tenho condições de assinar pois estou desempregado há anos e doaria dinheiro pra você continuar atualizando se eu tivesse, porém não tenho. Venho usando este método a mais ou menos dois ou três meses mas estou enfrentando o mesmo problema da galera ali em cima, no começo eu pensei que tinha alguma coisa a ver com todo mundo usando o mesmo site de gerar emails, porém mesmo criando um hotmail novo, o exitlag crasha do nada e diz que você tem 0 dias. Sei que é difícil pra você continuar trabalhando nisto sem estar ganhando nada mas você me ajudaria demais se continuasse!

Well, I see why u don't get a job, you are playing damn video games 🤣

Btw, if you have been unemployed for years, why didn't you study and became web dev? As I can expect, you do have access to internet and video games.

Do as u wish, just don't victim yourself to others. Also, please use English, even though I am Brazilian.

**Comment by gato-louco** [comment] 2021-10-30 13:19
> > > haiz
> > > tôi code fix bug này đây
> > 
> > Ow. So u probably know reverse engineering, assembly, C/C++, websocket connections, ways to get hwid and a bunch of experience.
> > 
> > Feel free to share your method with me (if it works, I just gonna keep it private, or as u wish) on my email (it is on my profile)
> 
> That's not me, that guy remade your work for his personality 

I saw it, no problem.

**Comment by gosu821** [comment] 2021-10-30 13:20
> > > > i found the way keep trials but it is just u playing video or use laptop, pc +when u create acc and use script to active 3 days, refresh tab for sure that 3 days then do not close that tab when u verifed and actived it or close your browser keep it open
> > > > ![hình ảnh_2021-10-30_181944](https://user-images.githubusercontent.com/58213619/139530907-83d1bf7b-ca12-406b-899b-4187e62d6f57.png) been using 5hours like that
> > > 
> > > 
> > > không ông à, tụi exitlag nó check hwid chứ nó không ngu như ông tưởng
> > 
> > 
> > thì như gato nói làm sao để biết rằng nó nghĩ mình dùng như 1 pc mới, chỉ hwid spoofer, và bỏ tiền mua
> > t thử lúc sau thì đúng 5 tiếng k sao, t tắt đi refresh lại được
> > đang thử spoofer của https://github.com/ALEHACKsp/hwid-bypass
> 
> Off course you can use a spoofer and create an account. The problem is, you are likely going to be banned from the games anti cheat if you use a spoofer

like u said before 4 options we need
so im just thinking about spoofer, ofc it's easy but the disadvantages spoofer coming in way to big, vangruard know that
just still find and wait some bright ideas

**Comment by gato-louco** [comment] 2021-10-30 13:24
I think I may have time to update it in 1 week, and it is going to take me a day or two.

Also, if I get no support, I will likely just sell the update to someone who is going to monopolize the sell of these accounts

**Comment by MohamedWSalah** [comment] 2021-10-30 13:26
> > > Current Exitlag account activator works this way:
> > > 
> > > * We connect to the websocket of exitlag login endpoint.
> > > * We send a message saying "Hey, I am logging from this computer. This is the password, this is the email and this is the HWID of the computer". The HWID we send is a random one.
> > > * ExitLag checks if the password and email matchs with one registered.
> > > * Then it checks if the HWID was already used once to login into an account.
> > > * If it was used before, so the user is trying to login with a computer that already got a trial.
> > > * If it wasn't used before, it saves the HWID and set as already used and activate 3 days trial.
> > > * Then, you login with a computer that the HWID was already saved as used [your computer], but once the account was already created with a random HWID, it just accepts.
> > > 
> > > Okay, what changed now is that the HWID used to create the account [we used a random one] must match to the one who is login in.
> > > So, what we need to do: Remember the first version o the HWID bypass, that is a executable? Well, it is going to be something similar.
> > > 
> > > * Reverse engineer the exitlag executable
> > > * Find where it gets the HWID
> > > * Make a random hwid and save it to a file [the filename could be hwid.txt].
> > > * Change the hwid before it is send to exitlag login.
> > > 
> > > Simple, but the Reverse engineer part isn't easy,
> > 
> > 
> > Gato, não sei você é brasileiro ou não mas esse projeto literalmente salvou minha vida cara, não tenho condições de assinar pois estou desempregado há anos e doaria dinheiro pra você continuar atualizando se eu tivesse, porém não tenho. Venho usando este método a mais ou menos dois ou três meses mas estou enfrentando o mesmo problema da galera ali em cima, no começo eu pensei que tinha alguma coisa a ver com todo mundo usando o mesmo site de gerar emails, porém mesmo criando um hotmail novo, o exitlag crasha do nada e diz que você tem 0 dias. Sei que é difícil pra você continuar trabalhando nisto sem estar ganhando nada mas você me ajudaria demais se continuasse!
> 
> Well, I see why u don't get a job, you are playing damn video games 🤣
> 
> Btw, if you have been unemployed for years, why didn't you study and became web dev? As I can expect, you do have access to internet and video games.
> 
> Do as u wish, just don't victim yourself to others. Also, please use English, even though I am Brazilian.

RESPECT !

**Comment by gato-louco** [comment] 2021-10-30 13:27
> > > > > i found the way keep trials but it is just u playing video or use laptop, pc +when u create acc and use script to active 3 days, refresh tab for sure that 3 days then do not close that tab when u verifed and actived it or close your browser keep it open
> > > > > ![hình ảnh_2021-10-30_181944](https://user-images.githubusercontent.com/58213619/139530907-83d1bf7b-ca12-406b-899b-4187e62d6f57.png) been using 5hours like that
> > > > 
> > > > 
> > > > không ông à, tụi exitlag nó check hwid chứ nó không ngu như ông tưởng
> > > 
> > > 
> > > thì như gato nói làm sao để biết rằng nó nghĩ mình dùng như 1 pc mới, chỉ hwid spoofer, và bỏ tiền mua
> > > t thử lúc sau thì đúng 5 tiếng k sao, t tắt đi refresh lại được
> > > đang thử spoofer của https://github.com/ALEHACKsp/hwid-bypass
> > 
> > Off course you can use a spoofer and create an account. The problem is, you are likely going to be banned from the games anti cheat if you use a spoofer
> 
> like u said before 4 options we need
> so im just thinking about spoofer, ofc it's easy but the disadvantages spoofer coming in way to big banned in game :D , vangruard know that
> just still find and wait some bright ideas

Also, if the spoofer changes the Hwid Everytime you open it, u will need create a new account also every time your restart the computer

**Comment by MohamedWSalah** [comment] 2021-10-30 13:32
gato, do you have discord ? Im interested in chatting with you and asking u about some stuff if u dont mind, unrelated to this repo.

**Comment by githubuser732** [comment] 2021-10-30 13:33
> > > Current Exitlag account activator works this way:
> > > 
> > > * We connect to the websocket of exitlag login endpoint.
> > > * We send a message saying "Hey, I am logging from this computer. This is the password, this is the email and this is the HWID of the computer". The HWID we send is a random one.
> > > * ExitLag checks if the password and email matchs with one registered.
> > > * Then it checks if the HWID was already used once to login into an account.
> > > * If it was used before, so the user is trying to login with a computer that already got a trial.
> > > * If it wasn't used before, it saves the HWID and set as already used and activate 3 days trial.
> > > * Then, you login with a computer that the HWID was already saved as used [your computer], but once the account was already created with a random HWID, it just accepts.
> > > 
> > > Okay, what changed now is that the HWID used to create the account [we used a random one] must match to the one who is login in.
> > > So, what we need to do: Remember the first version o the HWID bypass, that is a executable? Well, it is going to be something similar.
> > > 
> > > * Reverse engineer the exitlag executable
> > > * Find where it gets the HWID
> > > * Make a random hwid and save it to a file [the filename could be hwid.txt].
> > > * Change the hwid before it is send to exitlag login.
> > > 
> > > Simple, but the Reverse engineer part isn't easy,
> > 
> > 
> > Gato, não sei você é brasileiro ou não mas esse projeto literalmente salvou minha vida cara, não tenho condições de assinar pois estou desempregado há anos e doaria dinheiro pra você continuar atualizando se eu tivesse, porém não tenho. Venho usando este método a mais ou menos dois ou três meses mas estou enfrentando o mesmo problema da galera ali em cima, no começo eu pensei que tinha alguma coisa a ver com todo mundo usando o mesmo site de gerar emails, porém mesmo criando um hotmail novo, o exitlag crasha do nada e diz que você tem 0 dias. Sei que é difícil pra você continuar trabalhando nisto sem estar ganhando nada mas você me ajudaria demais se continuasse!
> 
> Well, I see why u don't get a job, you are playing damn video games 🤣
> 
> Btw, if you have been unemployed for years, why didn't you study and became web dev? As I can expect, you do have access to internet and video games.
> 
> Do as u wish, just don't victim yourself to others. Also, please use English, even though I am Brazilian.

Bro, I'm not trying to act like a victim but finding a job in a pandemic ain't that easy, like I said if I had money I would support you 100% and I'm grateful for you doing this for free, by the way I've been using a new account for a few hours now and haven't had any problems so it is really weird but I did change my IP though not sure if there's anything to do with that. I feel like exitlag has been using some method to detect accounts with the gatolouco password, I could be wrong! Anyways thank you again.

**Comment by gato-louco** [comment] 2021-10-30 13:34
> gato, do you have discord ? Im interested in chatting with you and asking u about some stuff if u dont mind, unrelated to this repo.

Sure, who doesn't have a discord?
Send me yours in my email

**Comment by gosu821** [comment] 2021-10-30 13:35
yeah, i argree big problem, spoofer has 2 sides 
but may i suggest?
like i was cheating valorant and apex before, 
guarded regions, like reversed
we will point throught that

**Comment by gosu821** [comment] 2021-10-30 13:37
> I think I may have time to update it in 1 week, and it is going to take me a day or two.
> 
> Also, if I get no support, I will likely just sell the update to someone who is going to monopolize the sell of these accounts

maybe i will paypal you doing this

**Comment by gato-louco** [comment] 2021-10-30 13:37
> > > > Current Exitlag account activator works this way:
> > > > 
> > > > * We connect to the websocket of exitlag login endpoint.
> > > > * We send a message saying "Hey, I am logging from this computer. This is the password, this is the email and this is the HWID of the computer". The HWID we send is a random one.
> > > > * ExitLag checks if the password and email matchs with one registered.
> > > > * Then it checks if the HWID was already used once to login into an account.
> > > > * If it was used before, so the user is trying to login with a computer that already got a trial.
> > > > * If it wasn't used before, it saves the HWID and set as already used and activate 3 days trial.
> > > > * Then, you login with a computer that the HWID was already saved as used [your computer], but once the account was already created with a random HWID, it just accepts.
> > > > 
> > > > Okay, what changed now is that the HWID used to create the account [we used a random one] must match to the one who is login in.
> > > > So, what we need to do: Remember the first version o the HWID bypass, that is a executable? Well, it is going to be something similar.
> > > > 
> > > > * Reverse engineer the exitlag executable
> > > > * Find where it gets the HWID
> > > > * Make a random hwid and save it to a file [the filename could be hwid.txt].
> > > > * Change the hwid before it is send to exitlag login.
> > > > 
> > > > Simple, but the Reverse engineer part isn't easy,
> > > 
> > > 
> > > Gato, não sei você é brasileiro ou não mas esse projeto literalmente salvou minha vida cara, não tenho condições de assinar pois estou desempregado há anos e doaria dinheiro pra você continuar atualizando se eu tivesse, porém não tenho. Venho usando este método a mais ou menos dois ou três meses mas estou enfrentando o mesmo problema da galera ali em cima, no começo eu pensei que tinha alguma coisa a ver com todo mundo usando o mesmo site de gerar emails, porém mesmo criando um hotmail novo, o exitlag crasha do nada e diz que você tem 0 dias. Sei que é difícil pra você continuar trabalhando nisto sem estar ganhando nada mas você me ajudaria demais se continuasse!
> > 
> > Well, I see why u don't get a job, you are playing damn video games 🤣
> > 
> > Btw, if you have been unemployed for years, why didn't you study and became web dev? As I can expect, you do have access to internet and video games.
> > 
> > Do as u wish, just don't victim yourself to others. Also, please use English, even though I am Brazilian.
> 
> Bro, I'm not trying to act like a victim but finding a job in a pandemic ain't that easy, like I said if I had money I would support you 100% and I'm grateful for you doing this for free, by the way I've been using a new account for a few hours now and haven't had any problems so it is really weird but I did change my IP though not sure if there's anything to do with that. I feel like exitlag has been using some method to detect accounts with the gatolouco password, I could be wrong! Anyways thank you again.

Try to change the password. Half of the hash is a md5 of the password gatolouco. Just change it to other (btw, I figured that out after I publish the repository)

**Comment by githubuser732** [comment] 2021-10-30 13:39
Also, I forgot to mention that I updated exitlag not sure if it helped but this account is working just fine now.

**Comment by gosu821** [comment] 2021-10-30 13:49
> > > > > Current Exitlag account activator works this way:
> > > > > 
> > > > > * We connect to the websocket of exitlag login endpoint.
> > > > > * We send a message saying "Hey, I am logging from this computer. This is the password, this is the email and this is the HWID of the computer". The HWID we send is a random one.
> > > > > * ExitLag checks if the password and email matchs with one registered.
> > > > > * Then it checks if the HWID was already used once to login into an account.
> > > > > * If it was used before, so the user is trying to login with a computer that already got a trial.
> > > > > * If it wasn't used before, it saves the HWID and set as already used and activate 3 days trial.
> > > > > * Then, you login with a computer that the HWID was already saved as used [your computer], but once the account was already created with a random HWID, it just accepts.
> > > > > 
> > > > > Okay, what changed now is that the HWID used to create the account [we used a random one] must match to the one who is login in.
> > > > > So, what we need to do: Remember the first version o the HWID bypass, that is a executable? Well, it is going to be something similar.
> > > > > 
> > > > > * Reverse engineer the exitlag executable
> > > > > * Find where it gets the HWID
> > > > > * Make a random hwid and save it to a file [the filename could be hwid.txt].
> > > > > * Change the hwid before it is send to exitlag login.
> > > > > 
> > > > > Simple, but the Reverse engineer part isn't easy,
> > > > 
> > > > 
> > > > Gato, não sei você é brasileiro ou não mas esse projeto literalmente salvou minha vida cara, não tenho condições de assinar pois estou desempregado há anos e doaria dinheiro pra você continuar atualizando se eu tivesse, porém não tenho. Venho usando este método a mais ou menos dois ou três meses mas estou enfrentando o mesmo problema da galera ali em cima, no começo eu pensei que tinha alguma coisa a ver com todo mundo usando o mesmo site de gerar emails, porém mesmo criando um hotmail novo, o exitlag crasha do nada e diz que você tem 0 dias. Sei que é difícil pra você continuar trabalhando nisto sem estar ganhando nada mas você me ajudaria demais se continuasse!
> > > 
> > > 
> > > Well, I see why u don't get a job, you are playing damn video games 🤣
> > > Btw, if you have been unemployed for years, why didn't you study and became web dev? As I can expect, you do have access to internet and video games.
> > > Do as u wish, just don't victim yourself to others. Also, please use English, even though I am Brazilian.
> > 
> > 
> > Bro, I'm not trying to act like a victim but finding a job in a pandemic ain't that easy, like I said if I had money I would support you 100% and I'm grateful for you doing this for free, by the way I've been using a new account for a few hours now and haven't had any problems so it is really weird but I did change my IP though not sure if there's anything to do with that. I feel like exitlag has been using some method to detect accounts with the gatolouco password, I could be wrong! Anyways thank you again.
> 
> Try to change the password. Half of the hash is a md5 of the password gatolouco. Just change it to other (btw, I figured that out after I publish the repository)

damn okiii man

**Comment by itsOwen** [comment] 2021-10-30 15:25
> I just remade it easy for those who are new to python men

copy-paste other people's work you are a joke nothing else.

**Comment by egorbaitceps** [comment] 2021-10-30 15:29
now simpler buy subscription than try to bypass it :/

**Comment by axtant** [comment] 2021-10-30 17:09
is there any other application which works like exit lag and fix routes,? or is there any other method i can fix routes?

**Comment by githubuser732** [comment] 2021-10-30 17:54
Account went RIP again after 5-6 hours of use when I had to restart my game! I wonder what they changed and what is causing this.

**Comment by gato-louco** [comment] 2021-10-30 18:13
Hey. I gonna lock this issue until tomorrow to avoid meaningless conversations.


I've said everything. Read all the messages if you have any doubts.

**Comment by sazukalu** [comment] 2021-11-03 23:59
hola, ha sido resuelto?

**Comment by sazukalu** [comment] 2021-11-04 00:00
hello, has it been resolved?

**Comment by gato-louco** [comment] 2021-11-04 01:14
Why don't you try it yourself?

No, it is not.

Also, what makes you think that i am going to release this publicly, since almost no one has donated yet?

Btw, contact me via email if you want to donate.

**Comment by Vinh1984** [comment] 2021-11-04 16:33
please help me! exitlag is too good to use for game entertainment.

**Comment by Vinh1984** [comment] 2021-11-04 16:33
please help me! exitlag is too good to use for game entertainment.

**Comment by gato-louco** [comment] 2021-11-04 21:43
Hey! 

I have decided.
I won't go public on the activator update.

**Closed by gato-louco** 2021-11-04 21:43 UTC
